import test from 'node:test';import assert from 'node:assert/strict';import {zipSync,strToU8} from 'fflate';
import {allowedDocumentUrl,fetchDocument,extractDocument} from '../lib/materials.js';import {normalizeTranscript,transcribe} from '../lib/transcribe.js';import {validateNotes} from '../lib/notes.js';import {newPair,pair,validateImport} from '../lib/portal.js';import {POST as transcribeRoute} from '../app/api/transcribe/route.js';import {collectVisibleMaterials} from '../extension/collector.js';
const good='https://cdn.filestackcontent.com/ABCDEFGHIJKLMNOPQRST';
test('PDF text extraction and cleanup complete successfully',async()=>{const stream='BT /F1 12 Tf 20 100 Td (Test slide) Tj ET';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 200] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];let pdf='%PDF-1.4\n';const offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=Buffer.byteLength(pdf);pdf+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(x=>`${String(x).padStart(10,'0')} 00000 n \n`).join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;const doc=await extractDocument(Buffer.from(pdf));assert.equal(doc.pages.length,1);assert.match(doc.pages[0].text,/Test slide/)});
test('document fetch blocks local addresses, credential URLs and transformed URLs',()=>{for(const u of ['http://127.0.0.1/test.pdf','https://cdn.filestackcontent.com.evil.test/ABCDEFGHIJKLMNOPQRST','https://user:pass@cdn.filestackcontent.com/ABCDEFGHIJKLMNOPQRST',good+'?secret=x',good+'/output=pdf'])assert.equal(allowedDocumentUrl(u),false);assert.equal(allowedDocumentUrl(good),true)});
test('document requests never follow redirects or use cookies',async()=>{await fetchDocument(good,async(u,o)=>{assert.equal(o.redirect,'error');assert.equal(o.credentials,'omit');return new Response('file')})});
test('unsupported URLs never make a network request',async()=>{let called=false;await assert.rejects(fetchDocument('http://localhost',()=>{called=true}));assert.equal(called,false)});
test('PPTX extraction preserves slide order and stable content IDs',async()=>{const bytes=Buffer.from(zipSync({'ppt/slides/slide2.xml':strToU8('<p:sld><a:t>Second slide</a:t></p:sld>'),'ppt/slides/slide1.xml':strToU8('<p:sld><a:t>First slide</a:t></p:sld>')}));const a=await extractDocument(bytes,'sample.pptx'),b=await extractDocument(bytes,'renamed.pptx');assert.equal(a.pages[0].text,'First slide');assert.equal(a.pages[1].text,'Second slide');assert.equal(a.id,b.id)});
test('rejects archives that are not presentations and invalid document bytes',async()=>{await assert.rejects(extractDocument(Buffer.from('not pdf')));await assert.rejects(extractDocument(Buffer.from(zipSync({'file.txt':strToU8('x')}))))});
test('rejects invalid transcript timestamps and empty speech',()=>{assert.throws(()=>normalizeTranscript({segments:[{start:4,end:2,text:'hello'}]}));assert.throws(()=>normalizeTranscript({segments:[]}));assert.throws(()=>normalizeTranscript({text:'missing timestamps'}))});
test('normalizes sample-relative timestamps without inventing video times',()=>{const t=normalizeTranscript({segments:[{start:1,end:3,text:' Hello '} ]});assert.deepEqual(t.segments,[{id:1,start:1,end:3,text:'Hello'}]);assert.match(t.clock,/not the portal/)});
test('transcription uses timestamped Whisper request and sanitizes quota failures',async()=>{const b=Buffer.alloc(110);b.writeUInt32BE(0x1a45dfa3);await assert.rejects(transcribe(b,'fake-test-key',async(url,o)=>{assert.equal(url,'https://api.openai.com/v1/audio/transcriptions');assert.equal(o.body.get('model'),'whisper-1');assert.equal(o.body.get('response_format'),'verbose_json');return new Response('secret',{status:429})}),/quota/)});
test('rejects uncited notes and lecture additions without transcript evidence',()=>{const m=[{id:'doc',pages:[{number:1,text:'x'}]}],s=[{id:1,start:0,end:1,text:'x'}];const section={heading:'Topic',kind:'addition',text:'x',sources:['doc:p1']};assert.throws(()=>validateNotes({sections:[section],limitations:[]},m,s));section.sources=['t999'];assert.throws(()=>validateNotes({sections:[section],limitations:[]},m,s));section.sources=['t1'];assert.equal(validateNotes({sections:[section],limitations:[]},m,s).sections.length,1)});
test('pairing tokens are unique, expire, and reject unrelated pages',()=>{const a=newPair(),b=newPair();assert.notEqual(a,b);assert.equal(a.length,48);pair(a).expires=0;assert.throws(()=>pair(a));assert.throws(()=>validateImport({sourceUrl:'https://unrelated.example',materials:[]}));assert.equal(validateImport({sourceUrl:good,materials:[{url:good}]}).materials.length,1)});
test('transcription endpoint rejects foreign origins before reading key or body',async()=>{const r=await transcribeRoute(new Request('http://localhost:3001/api/transcribe',{method:'POST',headers:{origin:'https://other.example'},body:'anything'}));assert.equal(r.status,403)});
test('connector only imports allowed visible links from Materials scope',()=>{const old={document:globalThis.document,location:globalThis.location,getComputedStyle:globalThis.getComputedStyle};try{const visible={getClientRects:()=>[1],closest:()=>null};const links=[{...visible,href:good,innerText:'Slides'},{...visible,href:'https://private.example',innerText:'Other'}];const scope={querySelector:()=>links[0],querySelectorAll:()=>links,textContent:'Materials'};const marker={...visible,textContent:'Materials',parentElement:scope,tagName:'H2'};globalThis.document={querySelectorAll:()=>[marker]};globalThis.location={href:'https://coach.mastersunion.org/academics-detail?courseCode=TEST',origin:'https://coach.mastersunion.org',pathname:'/academics-detail'};globalThis.getComputedStyle=()=>({visibility:'visible'});const r=collectVisibleMaterials();assert.deepEqual(r.materials,[{url:good,name:'Slides'}])}finally{Object.assign(globalThis,old)}});

 test('local origin aliases keep the same port and reject foreign origins',async()=>{const {sameOrigin}=await import('../lib/http.js');const req=o=>new Request('http://localhost:3001/api/materials',{headers:{origin:o}});assert.doesNotThrow(()=>sameOrigin(req('http://127.0.0.1:3001')));assert.throws(()=>sameOrigin(req('http://127.0.0.1:3002')));assert.throws(()=>sameOrigin(req('https://evil.example')));});
