'use client';
import {useEffect,useRef,useState} from 'react';
export default function LibraryBrowser({token,repository,onChoose,revision}){
 const [levels,setLevels]=useState([[],[],[]]),[chosen,setChosen]=useState(['','','']),[files,setFiles]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const generation=useRef(0);
 async function load(depth,path,selection){const id=++generation.current;setBusy(true);setError('');setFiles([]);try{const r=await fetch('/api/library',{method:'POST',headers:{'Content-Type':'application/json','x-github-token':token},body:JSON.stringify({action:'browse',repository,path})});const data=await r.json();if(!r.ok)throw Error(data.error||'Could not read library.');if(id!==generation.current)return;if(depth<3)setLevels(old=>old.map((rows,i)=>i===depth?data.folders:i>depth?[]:rows));else setFiles(data.files);if(depth===3)onChoose({term:selection[0],subject:selection[1],session:selection[2]});}catch(e){if(id===generation.current)setError(e.message)}finally{if(id===generation.current)setBusy(false)}}
 useEffect(()=>{setChosen(['','','']);setLevels([[],[],[]]);setFiles([]);if(repository&&token)load(0,'',[]);return()=>{generation.current++}},[repository,token,revision]);
 async function download(file){setBusy(true);setError('');try{const r=await fetch('/api/library',{method:'POST',headers:{'Content-Type':'application/json','x-github-token':token},body:JSON.stringify({action:'download',repository,path:file.path})});if(!r.ok){const data=await r.json();throw Error(data.error||'Download failed.')}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}catch(e){setError(e.message)}finally{setBusy(false)}}
 function select(depth,value){const next=chosen.map((v,i)=>i===depth?value:i>depth?'':v);setChosen(next);setLevels(old=>old.map((v,i)=>i>depth?[]:v));setFiles([]);if(value)load(depth+1,next.slice(0,depth+1).join('/'),next);else generation.current++}
 return <section><h3>Browse saved PDFs</h3><p>Download an existing summary immediately, without AI processing. If none exists, use Find your lecture to generate it.</p><p>Repository → Term → Subject (code) → Session number and name</p>{['Term','Subject (code)','Session'].map((label,i)=><label key={label}>{label}<select aria-label={`Library ${label}`} value={chosen[i]} disabled={busy||!levels[i].length} onChange={e=>select(i,e.target.value)}><option value="">Choose {label.toLowerCase()}</option>{levels[i].map(row=><option key={row.name} value={row.name}>{row.name}</option>)}</select></label>)}{busy&&<p role="status">Loading library…</p>}{error&&<p role="alert">{error}</p>}{!busy&&!error&&!levels[0].length&&<p>No saved term folders yet. Save your first session below.</p>}{files.map(file=><p key={file.name}><button className="primary" disabled={busy} onClick={()=>download(file)}>Download {file.name==='summary.pdf'?'saved session summary':file.name}</button></p>)}{chosen[2]&&!busy&&!files.some(f=>f.name==='summary.pdf')&&!error&&<p>No saved summary yet. Select this lecture above, import its transcript and materials, then generate notes.</p>}</section>
}
