 'use client';
import {useState,useRef,useEffect} from 'react';
import VideoCapture from './VideoCapture';
async function json(response){const body=await response.json();if(!response.ok)throw Error(body.error||'Request failed.');return body}
export default function PersonalWorkspace(){
 const [token,setToken]=useState(''),[verified,setVerified]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const attempt=useRef(0);
 function clear(){attempt.current++;setToken('');setVerified(false);setBusy(false);setMessage('Signed out.');}
 async function connect(e){e.preventDefault();const current=++attempt.current;setBusy(true);setVerified(false);setMessage('');try{await json(await fetch('/api/video-access',{method:'POST',headers:{'x-github-token':token}}));if(current===attempt.current){setVerified(true);setMessage('Account verified.');}}catch(e){if(current===attempt.current)setMessage(e.message);}finally{if(current===attempt.current)setBusy(false);}}
 return <section className="panel noPrint"><span className="eyebrow">YOUR ACCOUNT</span><h2>Personal workspace</h2><p>Connect your GitHub account to access your personal tools. Account access is checked securely before tools appear.</p>{!verified?<form onSubmit={connect}><p>Use a GitHub token with Email addresses read permission. Your university email must be verified on your GitHub account. The token stays in this tab’s memory and is cleared on reload.</p><a href="https://github.com/settings/emails" target="_blank" rel="noreferrer">Manage verified GitHub emails ↗</a><label>Personal account token<input type="password" autoComplete="off" value={token} onChange={e=>{attempt.current++;setToken(e.target.value);setVerified(false);setBusy(false);setMessage('');}}/></label><button className="primary" disabled={!token||busy}>{busy?'Verifying…':'Connect personal account'}</button></form>:<button className="secondary" onClick={clear}>Sign out of personal workspace</button>}{message&&<p role="status">{message}</p>}{verified&&<VideoCapture token={token}/>}</section>
}
