 'use client';
import {useState,useRef,useEffect} from 'react';
async function json(response){const body=await response.json();if(!response.ok)throw Error(body.error||'Request failed.');return body}
export default function PersonalWorkspace(){
 const [token,setToken]=useState(''),[verified,setVerified]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const attempt=useRef(0);
 function clear(){attempt.current++;setToken('');setVerified(false);setBusy(false);setMessage('Signed out.');}
 async function connect(e){e.preventDefault();const current=++attempt.current;setBusy(true);setVerified(false);setMessage('');try{await json(await fetch('/api/video-access',{method:'POST',headers:{'x-github-token':token}}));if(current===attempt.current){setVerified(true);setMessage('Account verified.');}}catch(e){if(current===attempt.current)setMessage(e.message);}finally{if(current===attempt.current)setBusy(false);}}
 return <section className="panel noPrint"><span className="eyebrow">YOUR ACCOUNT</span><h2>Personal workspace</h2><p>Connect your GitHub account to access your personal tools. Account access is checked securely before tools appear.</p>{!verified?<form onSubmit={connect}><p>Use a GitHub token with Email addresses read permission. Your university email must be verified on your GitHub account. The token stays in this tab’s memory and is cleared on reload.</p><a href="https://github.com/settings/emails" target="_blank" rel="noreferrer">Manage verified GitHub emails ↗</a><label>Personal account token<input type="password" autoComplete="off" value={token} onChange={e=>{attempt.current++;setToken(e.target.value);setVerified(false);setBusy(false);setMessage('');}}/></label><button className="primary" disabled={!token||busy}>{busy?'Verifying…':'Connect personal account'}</button></form>:<button className="secondary" onClick={clear}>Sign out of personal workspace</button>}{message&&<p role="status">{message}</p>}{verified&&<VideoCapture token={token}/>}</section>
}
function VideoCapture({token}){
 const [recording,setRecording]=useState(false),[url,setUrl]=useState(''),[message,setMessage]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false);const recorder=useRef(null),stream=useRef(null),timer=useRef(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop())}},[]);
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);
 function stop(){if(recorder.current?.state==='recording')recorder.current.stop()}
 async function start(){setBusy(true);setMessage('');try{await json(await fetch('/api/video-access',{method:'POST',headers:{'x-github-token':token}}));const media=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});stream.current=media;const type=['video/webm;codecs=vp8,opus','video/webm'].find(m=>MediaRecorder.isTypeSupported(m));if(!type)throw Error('Video recording is unavailable.');const r=new MediaRecorder(media,{mimeType:type,videoBitsPerSecond:800000,audioBitsPerSecond:64000}),chunks=[];let size=0;recorder.current=r;r.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);size+=e.data.size;if(size>=90*1024*1024){setMessage('Capture reached the 90 MB memory limit. Save this part before continuing.');stop()}}};r.onstop=()=>{clearTimeout(timer.current);media.getTracks().forEach(t=>t.stop());if(mounted.current){setRecording(false);setUrl(URL.createObjectURL(new Blob(chunks,{type})))}};r.onerror=()=>{setMessage('Recording failed. Review any saved portion.');stop()};media.getTracks().forEach(t=>t.addEventListener('ended',stop,{once:true}));setUrl('');r.start(1000);setRecording(true);timer.current=setTimeout(stop,30*60*1000)}catch(e){stream.current?.getTracks().forEach(t=>t.stop());setMessage(e.message)}finally{setBusy(false)}}
 return <section><h3>Personal video capture</h3><p>Save a permitted recording to this device, without AI processing. Stops after 30 minutes or 90 MB; save each part before continuing. Keep this page open. Videos are not uploaded to GitHub.</p><label className="check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>The university permits me to capture this recording.</label><button className="primary" disabled={!consent||recording||busy} onClick={start}>Capture video</button><button className="secondary" disabled={!recording} onClick={stop}>Stop video</button><p role="status">{recording?'Recording video…':message}</p>{url&&<><video controls src={url} style={{maxWidth:'100%'}}/><a className="secondary" href={url} download="lecture-video.webm">Download video</a></>}</section>
}
