import {lookup} from 'node:dns/promises';
import {request as httpsRequest} from 'node:https';
import {BlockList,isIP} from 'node:net';
import {InputError} from './http.js';
const blocked=new BlockList();
for(const [ip,prefix] of [['0.0.0.0',8],['10.0.0.0',8],['100.64.0.0',10],['127.0.0.0',8],['169.254.0.0',16],['172.16.0.0',12],['192.0.0.0',24],['192.0.2.0',24],['192.168.0.0',16],['198.18.0.0',15],['198.51.100.0',24],['203.0.113.0',24],['224.0.0.0',3]])blocked.addSubnet(ip,prefix);
export function publicIPv4(ip){return isIP(ip)===4&&!blocked.check(ip)}
export function endpoint(value){let u;try{u=new URL(value)}catch{throw new InputError('Enter a valid HTTPS API base URL.')}if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||(u.port&&u.port!=='443')||isIP(u.hostname)||!u.hostname.includes('.')||u.hostname.endsWith('.local'))throw new InputError('Use a public HTTPS provider hostname without credentials or query parameters.');return u.href.replace(/\/$/,'')}
// Pin the TLS connection to a validated public address. Never follow redirects.
export async function publicFetch(url,init={}){endpoint(url);const u=new URL(url);const addresses=await lookup(u.hostname,{all:true,family:4});if(!addresses.length||addresses.some(x=>!publicIPv4(x.address)))throw new InputError('Provider address must resolve to a public server.');const ip=addresses[0].address;const request=new Request(url,init);const bytes=request.body?Buffer.from(await request.arrayBuffer()):undefined;
return await new Promise((resolve,reject)=>{const req=httpsRequest(u,{method:request.method,headers:Object.fromEntries(request.headers),signal:init.signal,agent:false,lookup:(host,options,cb)=>options.all?cb(null,[{address:ip,family:4}]):cb(null,ip,4)},res=>{const chunks=[];let size=0;res.on('data',chunk=>{size+=chunk.length;if(size>8*1024*1024){res.destroy();reject(new InputError('Provider response too large.',502))}else chunks.push(chunk)});res.on('error',reject);res.on('end',()=>resolve(new Response([204,304].includes(res.statusCode)?null:Buffer.concat(chunks),{status:res.statusCode,headers:{'content-type':'application/json'}})))});req.on('error',reject);req.setTimeout(120000,()=>req.destroy(new Error('Provider timeout')));req.end(bytes)});
}
export function configuration(value={}){const provider=value.provider||'openai';if(!['openai','gemini','compatible'].includes(provider))throw new InputError('Choose a supported provider.');const baseUrl=provider==='openai'?'https://api.openai.com/v1':provider==='gemini'?'https://generativelanguage.googleapis.com/v1beta':endpoint(value.baseUrl);const model=value.model||(provider==='openai'?'gpt-4.1-mini':provider==='gemini'?'gemini-flash-latest':'');const audioModel=value.audioModel||(provider==='openai'?'whisper-1':provider==='gemini'?model:'');for(const m of [model,audioModel])if(typeof m!=='string'||m.length>160||/[\s?#]/.test(m))throw new InputError('Enter a valid model ID.');if(!model)throw new InputError('Enter your provider’s notes model ID.');return {provider,baseUrl,model,audioModel}}
export function fromHeaders(request){return configuration({provider:request.headers.get('x-provider'),baseUrl:request.headers.get('x-base-url'),model:request.headers.get('x-model'),audioModel:request.headers.get('x-audio-model')})}
export function transport(config,fetcher){return fetcher||(config.provider==='compatible'?publicFetch:fetch)}
export async function geminiJson(config,key,parts,schema,fetcher){const r=await transport(config,fetcher)(`${config.baseUrl}/models/${encodeURIComponent(config.model)}:generateContent`,{method:'POST',headers:{'x-goog-api-key':key,'Content-Type':'application/json'},redirect:'error',signal:AbortSignal.timeout(120000),body:JSON.stringify({contents:[{role:'user',parts}],generationConfig:{responseMimeType:'application/json',responseJsonSchema:schema,maxOutputTokens:8192}})});if(!r.ok)throw new InputError(r.status===400||r.status===401||r.status===403?'Google rejected the key, model or request. Check your Gemini API key and model access.':r.status===429?'Google quota or rate limit reached. Check AI Studio usage and billing.':'Google could not process this request.',502);const data=await r.json();const candidate=data.candidates?.[0];if(candidate?.finishReason!=='STOP')throw new InputError('Google did not return a complete result. Your sources are preserved.',502);try{return JSON.parse(candidate.content.parts.filter(p=>typeof p.text==='string'&&!p.thought).map(p=>p.text).join(''))}catch{throw new InputError('Google returned invalid structured output.',502)}}
